services:
  docs:
    image: vert_project_local_docs
    container_name: vert_project_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./vert_project:/app/vert_project:z
    ports:
      - '9000:9000'
    command: /start-docs
